version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo "Installing dependencies"
      - npm install 
  
  build:
    commands:
      - echo "Building the project"
      - npm run build
      - ls -l dist  # ✅ Debugging: List contents of dist folder
      - |
        if [ ! -d "dist" ]; then
          echo "❌ Error: dist/ folder missing!"
          exit 1
        fi

  post_build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - '**/*'
    - 'Procfile'
    - 'package.json'
    - 'node_modules/**/*'
  base-directory: .
  discard-paths: no
